#!/bin/sh
# Auto-generated by Game Launcher - runs one game, then the
# launcher loop in mux_launch.sh brings the launcher back.
. /opt/muos/script/var/func.sh
command -v SETUP_STAGE_OVERLAY >/dev/null 2>&1 && SETUP_STAGE_OVERLAY
command -v SETUP_SDL_ENVIRONMENT >/dev/null 2>&1 && SETUP_SDL_ENVIRONMENT
SET_VAR "system" "foreground_process" "retroarch" 2>/dev/null || SET_VAR "SYSTEM" "FOREGROUND_PROCESS" "retroarch"
HOME="$(GET_VAR "device" "board/home")"
export HOME
CORE_DIR="/opt/muos/share/core"
[ -d "$CORE_DIR" ] || CORE_DIR="$(GET_VAR "device" "storage/rom/mount")/MUOS/core"
RA_ARGS=""
command -v CONFIGURE_RETROARCH >/dev/null 2>&1 && RA_ARGS=$(CONFIGURE_RETROARCH)
retroarch $RA_ARGS -v -f -L "$CORE_DIR/mgba_libretro.so" '/Users/kevin/Documents/GitHub/muOS-GameLauncher/GAME/PokemonEmerald/Pokemon - Emerald Version (USA, Europe).gba'
