-- Builds and executes game launch commands.
--
-- On device (muOS): writes <appdir>/runtime/next_launch.sh then quits.
--   mux_launch.sh runs the script (RetroArch or a PortMaster .sh) and
--   relaunches this app when the game exits.
--
-- On macOS (local testing): runs RetroArch directly if installed, otherwise
--   simulates the launch. The launcher keeps running either way.

local Platform = require("src.platform")
local Config = require("src.config")
local State = require("src.state")
local Stats = require("src.stats")

local Launcher = {}

local esc = Platform.shellEscape

-- The shell command that starts the game (without any muOS setup).
-- With cores_dir = "auto", the core path uses the $CORE_DIR shell variable,
-- resolved on-device inside the generated launch script.
function Launcher.gameCommand(game)
    if game.isScript then
        -- Execute directly so the script's own shebang applies. PortMaster
        -- scripts are bash; running them with BusyBox sh would fail.
        return esc(game.romPath)
    end

    -- Standalone-emulator systems (e.g. PSP -> PPSSPP) go through muOS's
    -- own ext-* launch scripts, which take NAME CORE FILE arguments and
    -- do their full environment setup internally.
    local ext = Config.extLauncherForSystem(game.system)
    if ext then
        return string.format("%s %s %s %s",
            esc(ext.script), esc(game.name), esc(ext.core), esc(game.romPath))
    end

    local core = Config.coreForSystem(game.system)
    if not core then
        return nil, "No core mapped for system '" .. tostring(game.system) .. "' (edit defaults.cfg)"
    end

    local coreArg
    if Config.values.cores_dir == "auto" then
        coreArg = '"$CORE_DIR/' .. core .. '"'
    else
        coreArg = esc(Config.values.cores_dir .. "/" .. core)
    end
    return string.format("%s %s -L %s %s",
        Config.values.retroarch_bin,
        Config.values.retroarch_args or "",
        coreArg,
        esc(game.romPath))
end

local function writeDeviceLaunchScript(game, cmd)
    local appDir = Platform.appDir()
    Platform.mkdir(appDir .. "/runtime")

    -- Mirrors muOS's own libretro launcher (script/launch/lr-general.sh):
    -- overlay/SDL setup, foreground process, CONFIGURE_RETROARCH, HOME.
    local isExt = Config.extLauncherForSystem(game.system) ~= nil
    local isRetroarch = not game.isScript and not isExt
    -- "external" matches what muOS's own port launcher (ext-general.sh) sets
    local fg = game.isScript and "external" or "retroarch"
    local lines = {
        "#!/bin/sh",
        "# Auto-generated by Vitro Launcher - runs one game, then the",
        "# launcher loop in mux_launch.sh brings the launcher back.",
        ". /opt/muos/script/var/func.sh",
    }
    if not isExt then
        -- muOS ext-* scripts do their own overlay/SDL/HOME setup
        table.insert(lines, 'command -v SETUP_STAGE_OVERLAY >/dev/null 2>&1 && SETUP_STAGE_OVERLAY')
        table.insert(lines, 'command -v SETUP_SDL_ENVIRONMENT >/dev/null 2>&1 && SETUP_SDL_ENVIRONMENT')
        table.insert(lines, 'SET_VAR "system" "foreground_process" "' .. fg .. '" 2>/dev/null || SET_VAR "SYSTEM" "FOREGROUND_PROCESS" "' .. fg .. '"')
        table.insert(lines, 'HOME="$(GET_VAR "device" "board/home")"')
        table.insert(lines, "export HOME")
    end
    if game.isScript then
        -- mux_launch.sh exports these for Love2D; they must not leak into
        -- PortMaster scripts. XDG_DATA_HOME is how port scripts locate the
        -- PortMaster control folder, and LD_LIBRARY_PATH would shadow the
        -- port's bundled libraries.
        table.insert(lines, "unset XDG_DATA_HOME LD_LIBRARY_PATH LD_PRELOAD")
        -- PortMaster's control.txt derives the SD card that holds the
        -- port's data from the script's own path: path components 2+3 of
        -- $0 (e.g. "mnt/mmc" -> /mnt/mmc/ports/<port>). Run from inside
        -- our app folder that yields a bogus path like /run/muos/ports/,
        -- so run a temporary copy placed on the card that actually
        -- contains the port's data folder.
        table.insert(lines, "PORT_SH=" .. esc(game.romPath))
        table.insert(lines, 'chmod +x "$PORT_SH"')
        table.insert(lines, [[PORT_NAME=$(grep -o '\$directory/ports/[^"/]*' "$PORT_SH" | head -n1 | sed 's|.*/||')]])
        table.insert(lines, 'RUN_SH="$PORT_SH" CLEANUP=""')
        table.insert(lines, 'if [ -n "$PORT_NAME" ]; then')
        table.insert(lines, '    for MNT in /mnt/mmc /mnt/sdcard; do')
        table.insert(lines, '        [ -d "$MNT/ports/$PORT_NAME" ] || continue')
        table.insert(lines, '        STAGE="$MNT/ports/.vitrolauncher"')
        table.insert(lines, '        mkdir -p "$STAGE"')
        table.insert(lines, '        if cp -f "$PORT_SH" "$STAGE/"; then')
        table.insert(lines, '            RUN_SH="$STAGE/$(basename "$PORT_SH")"')
        table.insert(lines, '            CLEANUP="$STAGE"')
        table.insert(lines, '            chmod +x "$RUN_SH"')
        table.insert(lines, '        fi')
        table.insert(lines, '        break')
        table.insert(lines, '    done')
        table.insert(lines, 'fi')
        cmd = '"$RUN_SH"'
    end
    if isRetroarch then
        -- Resolve the libretro cores directory across muOS versions
        table.insert(lines, 'CORE_DIR="/opt/muos/share/core"')
        table.insert(lines, '[ -d "$CORE_DIR" ] || CORE_DIR="$(GET_VAR "device" "storage/rom/mount")/MUOS/core"')
        table.insert(lines, 'RA_ARGS=""')
        table.insert(lines, 'command -v CONFIGURE_RETROARCH >/dev/null 2>&1 && RA_ARGS=$(CONFIGURE_RETROARCH)')

        -- Per-launch RetroArch overrides, applied with --appendconfig so
        -- they only affect games started from this launcher. RetroArch
        -- gives appendconfig the highest precedence and muOS ships
        -- config_save_on_exit off, so nothing leaks into the saved
        -- config or into games launched from the muOS menu.
        local overrides = {}
        if Config.values.saves_in_game_dir then
            -- Battery saves and save states go next to the rom, i.e.
            -- into the game's folder, so the folder stays portable
            -- (saves_in_game_dir in defaults.cfg).
            table.insert(overrides, 'savefiles_in_content_dir = "true"')
            table.insert(overrides, 'savestates_in_content_dir = "true"')
            -- muOS ships sort_savefiles/savestates_enable on, which
            -- appends the core name to the directory even after the
            -- content-dir redirect (RetroArch applies sorting last), so
            -- files would land in <game folder>/mGBA/ instead of flat
            -- next to the rom - and a "<rom>.state.auto" dropped into
            -- the folder would never be found. Flat is what we want.
            table.insert(overrides, 'sort_savefiles_enable = "false"')
            table.insert(overrides, 'sort_savestates_enable = "false"')
            table.insert(overrides, 'sort_savefiles_by_content_enable = "false"')
            table.insert(overrides, 'sort_savestates_by_content_enable = "false"')
        end
        if Config.values.ra_menu_exit then
            -- Exit with MENU alone (ra_menu_exit in defaults.cfg).
            -- Rebinds exit to the hotkey modifier button itself. With
            -- the modifier gone every other stock hotkey would fire on
            -- a bare button press, so they are disabled alongside it.
            -- The MENU button id comes from the device's own config
            -- (8 on most devices) rather than being hardcoded.
            table.insert(lines, 'MENU_BTN=$(sed -n \'s/^input_enable_hotkey_btn = "\\(.*\\)"$/\\1/p\' "$DEVICE_CONTROL_DIR/retroarch.device.cfg" 2>/dev/null)')
            table.insert(lines, '{ [ -n "$MENU_BTN" ] && [ "$MENU_BTN" != "nul" ]; } || MENU_BTN=8')
            table.insert(overrides, 'input_enable_hotkey_btn = "nul"')
            table.insert(overrides, 'input_exit_emulator_btn = "$MENU_BTN"')
            table.insert(overrides, 'input_menu_toggle_btn = "nul"')
            table.insert(overrides, 'input_load_state_btn = "nul"')
            table.insert(overrides, 'input_save_state_btn = "nul"')
            table.insert(overrides, 'input_fps_toggle_btn = "nul"')
            table.insert(overrides, 'input_toggle_fast_forward_btn = "nul"')
            table.insert(overrides, 'input_toggle_slowmotion_btn = "nul"')
            table.insert(overrides, 'input_state_slot_decrease_btn = "nul"')
            table.insert(overrides, 'input_state_slot_increase_btn = "nul"')
        end
        if #overrides > 0 then
            -- /tmp keeps the path free of spaces: RA_ARGS is unquoted
            -- (matching lr-general.sh) and the app dir contains one.
            table.insert(lines, 'EXTRA_CFG="/tmp/vitrolauncher_extra.cfg"')
            table.insert(lines, 'cat >"$EXTRA_CFG" <<RAEOF')
            for _, override in ipairs(overrides) do
                table.insert(lines, override)
            end
            table.insert(lines, 'RAEOF')
            table.insert(lines, 'case "$RA_ARGS" in')
            table.insert(lines, '*--appendconfig=*) RA_ARGS="$RA_ARGS|$EXTRA_CFG" ;;')
            table.insert(lines, '*) RA_ARGS="$RA_ARGS --appendconfig=$EXTRA_CFG" ;;')
            table.insert(lines, 'esac')
        end
        -- RA_ARGS intentionally unquoted, matching lr-general.sh behaviour
        cmd = cmd:gsub("^" .. Config.values.retroarch_bin:gsub("%p", "%%%0") .. " ",
            Config.values.retroarch_bin .. " $RA_ARGS ")
    end
    table.insert(lines, cmd)
    if game.isScript then
        table.insert(lines, '[ -n "$CLEANUP" ] && rm -rf "$CLEANUP"')
    end
    local script = table.concat(lines, "\n") .. "\n"

    local path = appDir .. "/runtime/next_launch.sh"
    Platform.writeFile(path, script)
    os.execute("chmod +x " .. esc(path))
    return path
end

-- Returns: "quit" (device: app should exit so the loop runs the game),
--          "ran" (mac: game ran/simulated, keep the launcher open),
--          nil, err on failure.
function Launcher.launch(game)
    local cmd, err = Launcher.gameCommand(game)
    if not cmd then return nil, err end

    if not Platform.fileExists(game.romPath) then
        return nil, "File not found: " .. game.romPath
    end

    State.markPlayed(game.id)
    Stats.recordLaunch(game)

    if Platform.isDevice then
        writeDeviceLaunchScript(game, cmd)
        print("[Launcher] Wrote next_launch.sh, quitting to launch: " .. game.name)
        love.event.quit()
        return "quit"
        -- The play session stays open; the next launcher start closes it.
    end

    -- macOS: try a real local RetroArch, otherwise simulate
    local h = io.popen("command -v " .. Config.values.retroarch_bin .. " 2>/dev/null")
    local found = h and h:read("*l")
    if h then h:close() end

    local localCmd = cmd:gsub('"%$CORE_DIR/', '"/opt/muos/share/core/')
    if found and found ~= "" then
        print("[Launcher] Running locally: " .. localCmd)
        os.execute(localCmd)
    else
        print("[Launcher] (simulated) " .. localCmd)
    end
    -- Synchronous run: the session opened above can close immediately
    Stats.finishOpenSession()
    return "ran"
end

return Launcher
